ITServiceApp/Components/PricingTableViewComponent.cs
using AutoMapper;
using ITServiceApp.Data;
using ITServiceApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITServiceApp.Components
{
    public class PricingTableViewComponent:ViewComponent
    {
        private readonly MyContext _dbContext;
        private readonly IMapper _mapper;

        public PricingTableViewComponent(MyContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            var data = _dbContext.SubscriptionTypes.OrderBy(x => x.Price).ToList().Select(x => _mapper.Map<SubscriptionTypeViewModel>(x)).ToList();
            return View(data);
        }
    }
}

ITServiceApp/Controllers/HomeController.cs
using AutoMapper;
using ITServiceApp.Data;
using ITServiceApp.Models.Entities;
using ITServiceApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITServiceApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly MyContext _dbContext;
        private readonly IMapper _mapper;
        public HomeController(MyContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }
        public IActionResult Index()
        {

            //var data = _dbContext.SubscriptionTypes.OrderBy(x => x.Price).ToList().Select(x=>_mapper.Map<SubscriptionTypeViewModel>(x)).ToList();  1.yol

            //var model = new List<SubscriptionTypeViewModel>();

            //var query = _dbContext.SubscriptionTypes.OrderBy(x => x.Price).ToList();

            //foreach (var item in query)              ---------------- Uzun YOl-------------
            //{
            //    var dataItem = _mapper.Map<SubscriptionTypeViewModel>(SubscriptionType);
            //    model.Add(dataItem);
            //}

            return View();
        }
    }
}

ITServiceApp/Views/Home/Index.cshtml
@model List<SubscriptionTypeViewModel> 

@{
    ViewBag.Title = "AnaSayfa";
}

<!--====== Banner Slider Start ======-->
<section class="banner-slider banner-slider-one banner-slider-active">
    <div class="single-banner">
        <div class="container-fluid container-1470">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <div class="banner-text">
                        <div class="banner-content">
                            <span data-animation="fadeInUp" data-delay="0.3s" class="title-tag">
                                IT Business Consulting
                            </span>
                            <h1 data-animation="fadeInLeft" data-delay="0.6s" class="title">
                                Best IT Soluations Provider Agency
                            </h1>
                            <p data-animation="fadeInLeft" data-delay=".9s">
                                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremda tium totam rem aperiam eaque ipsa quae ab illo inventore veritatis
                            </p>
                            <a data-animation="fadeInUp" data-delay="1.1s" class="main-btn rounded-btn icon-right small-size" href="services.html">
                                Our Services <i class="fal fa-long-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 d-none d-lg-block">
                    <div class="banner-img" data-animation="fadeInRight" data-delay="0.5s">
                        <img src="assets/img/banner/banner-img.png" alt="Banner">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="single-banner">
        <div class="container-fluid container-1470">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <div class="banner-text">
                        <div class="banner-content">
                            <span data-animation="fadeInUp" data-delay="0.3s" class="title-tag">
                                IT Business Consulting
                            </span>
                            <h1 data-animation="fadeInLeft" data-delay="0.6s" class="title">
                                Best IT Soluations Provider Agency
                            </h1>
                            <p data-animation="fadeInLeft" data-delay=".9s">
                                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremda tium totam rem aperiam eaque ipsa quae ab illo inventore veritatis
                            </p>
                            <a data-animation="fadeInUp" data-delay="1.1s" class="main-btn rounded-btn icon-right small-size" href="services.html">
                                Our Services <i class="fal fa-long-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 d-none d-lg-block">
                    <div class="banner-img" data-animation="fadeInRight" data-delay="0.5s">
                        <img src="assets/img/banner/banner-img.png" alt="Banner">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--====== Banner Slider End ======-->


@*<partial name="Partials/_PricingTable" model="Model"/>*@
@await Component.InvokeAsync("PricingTable")