Ilk_Mvc_Projesi/Models/Employee.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Ilk_Mvc_Projesi.Models
{
    public partial class Employee
    {
        public Employee()
        {
            EmployeeTerritories = new HashSet<EmployeeTerritory>();
            InverseReportsToNavigation = new HashSet<Employee>();
            Orders = new HashSet<Order>();
        }

        public int EmployeeId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public string TitleOfCourtesy { get; set; }
        public DateTime? BirthDate { get; set; }
        public DateTime? HireDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string Extension { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public int? ReportsTo { get; set; }
        public string PhotoPath { get; set; }

        public virtual Employee ReportsToNavigation { get; set; }
        public virtual ICollection<EmployeeTerritory> EmployeeTerritories { get; set; }
        public virtual ICollection<Employee> InverseReportsToNavigation { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}

Ilk_Mvc_Projesi/ViewModels/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ilk_Mvc_Projesi.ViewModels
{
    public class EmployeeViewModel
    {
        [Required(ErrorMessage = "Bu alan boş bırakalamaz")]
        [Display(Name = "Adı")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakalamaz")]
        [Display(Name = "Soyadı")]
        public string LastName { get; set; }
        [Display(Name = "Kıdemi")]
        public string Title { get; set; }

        public int EmployeeId { get; set; }
    }
}

Ilk_Mvc_Projesi/Controllers/EmployeeController.cs
using Ilk_Mvc_Projesi.Models;
using Ilk_Mvc_Projesi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Project1.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly NorthwindContext _context;
        public EmployeeController(NorthwindContext context)
        {
            _context = context;
        }
        private int _pageSize = 5;

        public IActionResult Index(int? page = 1)
        {
            var model = _context.Employees
                .Include(x => x.Orders)
                .ThenInclude(x => x.OrderDetails)
                .ThenInclude(x => x.Product)
                .OrderBy(x => x.FirstName)
                .Skip((page.GetValueOrDefault() - 1) * _pageSize)
                .Take(_pageSize)
                .ToList();

            ViewBag.Page = page.GetValueOrDefault(1);
            ViewBag.Limit = (int)Math.Ceiling(_context.Employees.Count() / (double)_pageSize);
            return View(model);
        }

        public IActionResult Detail(int? id)
        {
            var model = _context.Employees.Include(x => x.Orders).ThenInclude(x => x.OrderDetails).ThenInclude(x => x.Product).FirstOrDefault(x => x.EmployeeId == id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            var employee = new Employee()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Title = model.Title
            };

            _context.Employees.Add(employee);
            try
            {
                _context.SaveChanges();
                return RedirectToAction(nameof(Detail), new { id = employee.EmployeeId });
            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, $"{model.FirstName} eklenirken bir hata oluştu. Tekrar Deneyin");
                ModelState.AddModelError(string.Empty, $"{model.LastName} eklenirken bir hata oluştu. Tekrar Deneyin");
                ModelState.AddModelError(string.Empty, $"{model.Title} eklenirken bir hata oluştu. Tekrar Deneyin");
                return View(model);
            }
        }

        public IActionResult Delete(int? employeeId)
        {
            var silinecek = _context.Employees.FirstOrDefault(x => x.EmployeeId == employeeId);

            try
            {
                _context.Employees.Remove(silinecek);
                _context.SaveChanges();
            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }
            TempData["silinen_employee"] = silinecek.FirstName;
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            var employee = _context.Employees.FirstOrDefault(x => x.EmployeeId == id);
            if (employee == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new EmployeeViewModel()
            {
                EmployeeId = employee.EmployeeId,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                Title = employee.Title
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(EmployeeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            var employee = _context.Employees.FirstOrDefault(x => x.EmployeeId == model.EmployeeId);

            try
            {
                employee.FirstName = model.FirstName;
                employee.LastName = model.LastName;
                employee.Title = model.Title;
                _context.Update(employee);
                _context.SaveChanges();
                return RedirectToAction(nameof(Detail), new { id = employee.EmployeeId });
            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, $"{model.FirstName} eklenirken bir hata oluştu. Tekrar Deneyin");
                ModelState.AddModelError(string.Empty, $"{model.LastName} eklenirken bir hata oluştu. Tekrar Deneyin");
                ModelState.AddModelError(string.Empty, $"{model.Title} eklenirken bir hata oluştu. Tekrar Deneyin");
                return View(model);
            }
        }
    }
}

Ilk_Mvc_Projesi/Views/Employee/Create.cshtml
@model EmployeeViewModel

<div class="text-danger">
    <div asp-validation-summary="All"></div>
</div>

<form method="post" asp-action="Create" asp-controller="Employee">
    <label asp-for="FirstName"></label>
    <input asp-for="FirstName" />
    <span class="text-danger" asp-validation-for="FirstName"></span>
    <br />

    <label asp-for="LastName"></label>
    <input asp-for="LastName" />
    <span class="text-danger" asp-validation-for="LastName"></span>
    <br />

    <label asp-for="Title"></label>
    <input asp-for="Title" />
    <span class="text-danger" asp-validation-for="Title"></span>
    <br />
    <input type="submit" value="Ekle" class="btn btn-success" />

</form>

Ilk_Mvc_Projesi/Views/Employee/Detail.cshtml
@model Employee




<a asp-action="Delete" asp-controller="Employee" asp-route-employeeId="@Model.EmployeeId" class="btn btn-danger">Çalışanı Sil</a>
<a asp-action="Update" asp-controller="Employee" asp-route-id="@Model.EmployeeId" class="btn btn-danger">Çalışanı Güncelle</a>

<div class="row">
    <div class="col-12">
        <table class="table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Sipariş Tarihi</th>
                    <th>Sipariş Sayısı</th>
                    <th>Fiyat</th>
                    <th>Gönderilme Tarihi</th>
                    <th>Gönderildiği şehir</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.Orders)
                {

                    <tr>
                        <td>@item.OrderId</td>
                        <td>@item.OrderDate</td>
                        <td>@item.ShipVia</td>
                        <td>@item.Freight</td>
                        <td>@item.ShippedDate</td>
                        <td>@item.ShipCity</td>

                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

Ilk_Mvc_Projesi/Views/Employee/Index.cshtml
@model List<Employee>

<h1>Çalışanlar</h1>
<h2>Toplam Kayıt:@Model.Count</h2>
<a asp-action="Create" asp-controller="Employee" class="btn btn-success">Çalışan Ekle</a>

<div class="row">
    <div class="col-9">
        <table class="table-bordered">
            <thead>
                <tr>
                    <th>Adı</th>
                    <th>Soyadı</th>
                    <th>Kıdemi</th>
                    <th>Detay</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.FirstName</td>
                        <td>@item.LastName</td>
                        <td>@item.Title</td>
                        <th><a asp-action="Detail" asp-controller="Employee" asp-route-id="@item.EmployeeId" class="btn btn-block btn-primary">Detay</a></th>
                    </tr>
                }
            </tbody>
        </table>
        <input type="button" value="<" class="btn btn-success" id="btn-onceki"/>
        @ViewBag.Page/@ViewBag.Limit
        <input type="button" value=">" class="btn btn-success" id="btn-sonraki" />
    </div>
</div>

@section Scripts{ 
<script>
    var limit = @ViewBag.Limit;
    var page = @ViewBag.Page;
    $("#btn-onceki").click(function () {
        if (page > 1) {
            //page -= 1;
            //var url2 = "Employee/Index?page=" + page
            var url ='@Url.Action("Index", "Employee", new { page = ViewBag.Page - 1 })';
            window.location.href = url;
        }
    });

    $("#btn-sonraki").click(function () {
        if (page < limit) {
            var url = '@Url.Action("Index", "Employee", new { page = ViewBag.Page + 1 })';
            window.location.href = url;
        }
    });

</script>
}

Ilk_Mvc_Projesi/Views/Employee/Update.cshtml
@model EmployeeViewModel

<div class="text-danger">
    <div asp-validation-summary="All"></div>
</div>

<form method="post" asp-action="Update" asp-controller="Employee">
    <input asp-for="EmployeeId" type="hidden" />
    <label asp-for="FirstName"></label>
    <input asp-for="FirstName" />
    <span class="text-danger" asp-validation-for="FirstName"></span>
    <br />

    <label asp-for="LastName"></label>
    <input asp-for="LastName" />
    <span class="text-danger" asp-validation-for="LastName"></span>
    <br />

    <label asp-for="Title"></label>
    <input asp-for="Title" />
    <span class="text-danger" asp-validation-for="Title"></span>
    <br />
    <input type="submit" value="Guncelle" class="btn btn-success" />

</form>