Ilk_Mvc_Projesi/Models/Shipper.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Ilk_Mvc_Projesi.Models
{
    public partial class Shipper
    {
        public Shipper()
        {
            Orders = new HashSet<Order>();
        }

        public int ShipperId { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}

Ilk_Mvc_Projesi/ViewModels/ShipperViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ilk_Mvc_Projesi.ViewModels
{
    public class ShipperViewModel
    {

        public int ShipperId { get; set; }
        [StringLength(40, ErrorMessage = "Şirket adı 40 karakterden fazla olamaz.")]
        [Required(ErrorMessage = "Bu Alan Boş Olamaz")]
        public string CompanyName { get; set; }
        [StringLength(15, ErrorMessage = "Telefon numarası 15 karakterden fazla olamaz.")]
        public string Phone { get; set; }
    }
}

Ilk_Mvc_Projesi/Controllers/ShipperController.cs
using Ilk_Mvc_Projesi.Models;
using Ilk_Mvc_Projesi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Project1.Controllers
{
    public class ShipperController : Controller
    {
        private readonly NorthwindContext _context;
        public ShipperController(NorthwindContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var model = _context.Shippers.Include(x => x.Orders).ThenInclude(x => x.OrderDetails).OrderBy(x => x.CompanyName).ToList();
            return View(model);
        }

        public IActionResult Detail(int? id)
        {
            var shipper = _context.Shippers.Include(x => x.Orders).ThenInclude(x => x.OrderDetails).FirstOrDefault(x => x.ShipperId == id);
            if (shipper == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(shipper);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(ShipperViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(model));
            }

            var shipper = new Shipper()
            {
                CompanyName = model.CompanyName,
                Phone = model.Phone
            };
            _context.Shippers.Add(shipper);
            try
            {
                _context.SaveChanges();
                return RedirectToAction(nameof(Detail), new { id = shipper.ShipperId });
            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, $"{model.CompanyName} eklenirken Hata oluştu.");
                return View(model);
            }
        }

        public IActionResult Delete(int? shipperId)
        {
            var silinecek = _context.Shippers.FirstOrDefault(x => x.ShipperId == shipperId);
            if (silinecek == null)
            {
                return RedirectToAction(nameof(Index));
            }
            try
            {
                _context.Shippers.Remove(silinecek);
                _context.SaveChanges();

            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }
            TempData["silinen_shipper"] = silinecek.CompanyName;
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            var shipper = _context.Shippers.FirstOrDefault(x => x.ShipperId == id);
            if (shipper == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ShipperViewModel()
            {
                ShipperId = shipper.ShipperId,
                CompanyName = shipper.CompanyName,
                Phone = shipper.Phone
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(ShipperViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var shipper = _context.Shippers.FirstOrDefault(x => x.ShipperId == model.ShipperId);
            try
            {
                shipper.CompanyName = model.CompanyName;
                shipper.Phone = model.Phone;
                _context.Shippers.Update(shipper);
                _context.SaveChanges();
                return RedirectToAction(nameof(Detail), new { id = shipper.ShipperId });
            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, $"{model.CompanyName} eklenirken Hata oluştu.");
                return View(model);
            }
        }
    }
}

Ilk_Mvc_Projesi/Views/Shipper/Create.cshtml
@model ShipperViewModel

<div class="text-danger">
    <div asp-validation-summary="All"></div>
</div>

<form method="post" asp-action="Create" asp-controller="Shipper">
    <label asp-for="CompanyName"></label>
    <input asp-for="CompanyName" />
    <span class="text-danger" asp-validation-for="CompanyName"></span>
    <br />
    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <span class="text-danger" asp-validation-for="Phone"></span>
    <br />
    <input type="submit" value="Ekle" class="btn btn-primary" />
</form>

Ilk_Mvc_Projesi/Views/Shipper/Detail.cshtml
@model Shipper

<a asp-controller="Shipper" asp-action="Delete" asp-route-shipperId="@Model.ShipperId" class="btn btn-danger">Sil</a>
<a asp-controller="Shipper" asp-action="Update" asp-route-id="@Model.ShipperId" class="btn btn-warning">Guncelle</a>

<div class="row">
    <div class="col-9">
        <table class="table-bordered">
            <thead>
                <tr>
                    <th>Sipariş No</th>
                    <th>Toplam Satış Sayısı</th>
                    <th>Net Satış fiyatı</th>
                    <th>Sipariş Tarihi</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Orders)
                {
                    <tr>
                        <td>@item.OrderId</td>
                        <td>@item.OrderDetails.Count()</td>
                        <td>@item.OrderDetails.Sum(x => x.UnitPrice * x.Quantity * (decimal)(1 - x.Discount))</td>
                        <td>@item.OrderDate</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Ilk_Mvc_Projesi/Views/Shipper/Index.cshtml
@model List<Shipper>

@{
    var silinenMesaj = TempData["silinen_shipper"]?.ToString();
}
@if (!string.IsNullOrEmpty(silinenMesaj))
{
    <h3 class="text-danger"> @silinenMesaj Adlı Kargo Şirketi Silindi.</h3>
}

<h1>Kargo Şirketleri</h1>
<a asp-action="Create" asp-controller="Shipper" class="btn btn-success">Ekle</a>
<div class="row">
    <div class="col-9">
        <table class="table-bordered">
            <thead>
                <tr>
                    <th>Şirket Adı</th>
                    <th>iletişim</th>
                    <th>Detay</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CompanyName</td>
                        <td>@item.Phone</td>
                        <td><a asp-action="Detail" asp-controller="Shipper" asp-route-id="@item.ShipperId" class="btn btn-block btn-primary">Detay</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Ilk_Mvc_Projesi/Views/Shipper/Update.cshtml
@model ShipperViewModel

<div class="text-danger">
    <div asp-validation-summary="All"></div>
</div>

<form method="post" asp-action="Update" asp-controller="Shipper">
    <input asp-for="ShipperId" type="hidden" />
    <label asp-for="CompanyName"></label>
    <input asp-for="CompanyName" />
    <span class="text-danger" asp-validation-for="CompanyName"></span>
    <br />
    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <span class="text-danger" asp-validation-for="Phone"></span>
    <br />
    <input type="submit" value="Guncelle" class="btn btn-primary" />
</form>