Ilk_Mvc_Projesi/Models/Product.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Ilk_Mvc_Projesi.Models
{
    public partial class Product
    {
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? SupplierId { get; set; }
        public int? CategoryId { get; set; }
        public string QuantityPerUnit { get; set; }
        public decimal? UnitPrice { get; set; }
        public short? UnitsInStock { get; set; }
        public short? UnitsOnOrder { get; set; }
        public short? ReorderLevel { get; set; }
        public bool Discontinued { get; set; }

        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Ilk_Mvc_Projesi/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ilk_Mvc_Projesi.ViewModels
{
    public class ProductViewModel
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage ="Bu alan boş olamaz")]
        public string ProductName { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int? supplierId { get; set; }
        public string CompanyName { get; set; }
        [Range(0,999999999,ErrorMessage = "Ürün Fiyatı 0-999999999 olmalı.")]
        public decimal? UnitPrice { get; set; }

    }
}

Ilk_Mvc_Projesi/Controllers/ProductController.cs
using Ilk_Mvc_Projesi.Models;
using Ilk_Mvc_Projesi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc_Project1.Controllers
{
    public class ProductController : Controller
    {
        private readonly NorthwindContext _context;

        public ProductController(NorthwindContext context)
        {
            _context = context;
        }

        private int _pageSize = 10;
        public IActionResult Index(int? page = 1)
        {
            var model = _context.Products
                .Include(x => x.Category)
                .Include(x => x.Supplier)
                .OrderBy(x => x.Category.CategoryName)
                .ThenBy(x => x.ProductName)
                .Skip((page.GetValueOrDefault() - 1) * _pageSize) // 3. sayfanın verileri 20den başlması lazım o yüzden böyle yaptık
                .Take(_pageSize)
                .ToList();

            //ViewBag.Categories = _context.Categories.OrderBy(x => x.CategoryName).ToList();
            //ViewBag.Suppliers = _context.Suppliers.OrderBy(x => x.CompanyName).ToList();

            ViewBag.Page = page.GetValueOrDefault(1);
            ViewBag.Limit = (int)Math.Ceiling(_context.Products.Count() / (double)_pageSize); //math.ceiling yukarı yuvarlama işlemi yapar.
            return View(model);
        }

        public IActionResult Detail(int? id)
        {
            var data = _context.Products
                .Include(x => x.Category)
                .Include(x => x.Supplier)
                .FirstOrDefault(x => x.ProductId == id);

            if (data == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ProductViewModel()
            {
                ProductId = data.ProductId,
                ProductName = data.ProductName,
                CategoryId = data.CategoryId,
                CategoryName = data.Category.CategoryName,
                supplierId = data.SupplierId,
                CompanyName = data.Supplier?.CompanyName,
                UnitPrice = data.UnitPrice
            };
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.CategoryList = GetCategoryList();
            ViewBag.SupplierList = GetSupplierList();
            return View();
            
        }

        [HttpPost]
        public IActionResult Create(ProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.CategoryList = GetCategoryList();
                ViewBag.SupplierList = GetSupplierList();
                return View(model);
            }


            var product = new Product()
            {
                ProductName = model.ProductName,
                CategoryId = model.CategoryId,
                SupplierId = model.supplierId,
                UnitPrice = model.UnitPrice

            };
            
            try
            {
                _context.Products.Add(product);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index), new { id = product.ProductId });
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                ViewBag.CategoryList = GetCategoryList();
                ViewBag.SupplierList = GetSupplierList();
                return View(model);
            }
        }

        public IActionResult Update(int? id)
        {
            var data = _context.Products
                .Include(x => x.Category)
                .Include(x => x.Supplier)
                .FirstOrDefault(x => x.ProductId == id);

            if (data == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ProductViewModel()
            {
                ProductId = data.ProductId,
                ProductName = data.ProductName,
                CategoryId = data.CategoryId,
                CategoryName = data.Category.CategoryName,
                supplierId = data.SupplierId,
                CompanyName = data.Supplier?.CompanyName,
                UnitPrice = data.UnitPrice
            };
            //burdan sonrası comboboxları eklemek için method yaptık yaptık

            ViewBag.CategoryList = GetCategoryList();
            ViewBag.SupplierList = GetSupplierList();

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(ProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.CategoryList = GetCategoryList();
                ViewBag.SupplierList = GetSupplierList();
                return View(model);
            }

            var product = _context.Products.FirstOrDefault(x => x.ProductId == model.ProductId);
            if (product == null)
            {
                return RedirectToAction(nameof(Index));
            }
            product.ProductName = model.ProductName;
            product.UnitPrice = model.UnitPrice;
            product.CategoryId = model.CategoryId;
            product.SupplierId = model.supplierId;
            try
            {

                _context.Products.Update(product);
                _context.SaveChanges();
                TempData["Mesaj"] = $"{product.ProductName} ürünü başarı ile güncellendi";
                return RedirectToAction(nameof(Detail), new { id = product.ProductId });
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                ViewBag.CategoryList = GetCategoryList();
                ViewBag.SupplierList = GetSupplierList();
                return View(model);
            }

        }
        public IActionResult Delete(int? id)
        {
            var product = _context.Products.FirstOrDefault(x => x.ProductId == id);
            if (product == null)
            {
                return RedirectToAction(nameof(Index));
            }
            try
            {
                _context.Products.Remove(product);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Detail), new { id = product.ProductId });
            }

        }

        private List<SelectListItem> GetCategoryList()
        {
            var categories = _context.Categories.OrderBy(x => x.CategoryName).ToList(); //categories'in içinde veritabanından Categoty tablosunu attık

            var categoryList = new List<SelectListItem>() //categorylist listeli oluşturduk tipi selectListItem
            {
                new SelectListItem("Kategori yok",null) //comboboxa gelecek ad ve karşılığındaki id bir tane oluşturduk
            };

            foreach (var category in categories) //foreachle categoryliste categories içindeki category adı ve idleri atadık
            {
                categoryList.Add(new SelectListItem(category.CategoryName, category.CategoryId.ToString())); //buradan category combosu için ekleme işlemi yaptık foreachle kaç tane varsa eklicek.
            }
            return categoryList;
        }
        private List<SelectListItem> GetSupplierList() //yukarıdakilerin aynısı
        {
            var suppliers = _context.Suppliers.OrderBy(x => x.CompanyName).ToList();

            //aynısını Supllier içinde yaptık.
            var supplierList = new List<SelectListItem>()
            {
                new SelectListItem("Tedarikçi yok",null)
            };

            foreach (var supplier in suppliers)
            {
                supplierList.Add(new SelectListItem(supplier.CompanyName, supplier.SupplierId.ToString()));
            }

            return supplierList;
        }
    }
}

Ilk_Mvc_Projesi/Views/Product/Create.cshtml
@model ProductViewModel

<div class="bg-danger">
    <div asp-validation-summary="All">
    </div>
</div>

<form method="post" asp-action="Create" asp-controller="Product">
    <div class="row">
        <div class="col-3 text-black-50">Ürün Adı</div>
        <div class="col-3">
            <input asp-for="ProductName" class="form-control" />
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50">Fiyat</div>
        <div class="col-3">
            <input asp-for="UnitPrice" class="form-control" />
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50">Kategorisi</div>
        <div class="col-3">
            <select asp-for="CategoryId" asp-items="ViewBag.CategoryList" class="form-control"></select> @*KategoriId ve ViewBag eşleştiğinde gelicek*@
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50">Tedarikçi Firma</div>
        <div class="col-3">
            <select asp-for="supplierId" asp-items="ViewBag.SupplierList" class="form-control"></select>
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50"></div>
        <div class="col-5">
            <input type="submit" value="Ekle" class="btn btn-danger" />
        </div>
    </div>
</form>

Ilk_Mvc_Projesi/Views/Product/Detail.cshtml
@model ProductViewModel

<h1>@Model.ProductName</h1>
<h3>@($"{Model.UnitPrice:c2}")</h3>

<div class="bg-info">@TempData["Mesaj"]</div>  @*Aşağıdaki ile aynı*@


@*@{
        var guncellenenMesaj = @TempData["Mesaj"]?.ToString();
    }
    @if (!string.IsNullOrEmpty(guncellenenMesaj))
    {
        <h3 class="text-danger">@guncellenenMesaj</h3>
    }*@

<div class="row">
    <div class="col-3 text-black-50">Kategori Adı</div>
    <div class="col-3">@(Model.CategoryId == null ? "Kategorisi Yok" : Model.CategoryName)</div>
</div>

<div class="row">
    <div class="col-3 text-black-50">Tedarikçi Firma</div>
    <div class="col-3">@(Model.supplierId == null ? "Tedarikçi firma yok" : Model.CompanyName)</div>
</div>

<div class="row">
    <div class="col-3 text-black-50"></div>
    <div class="col-5">
        <a asp-action="Update" asp-controller="Product" asp-route-id="@Model.ProductId" class="btn btn-warning">
            Düzenle
        </a>
    </div>
    <div class="col">
        <input type="button" class="btn btn-danger" value="Sil" data-toggle="modal" data-target="#confirm-delete" />
    </div>
</div>

<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Silme Onayı</h4>
            </div>

            <div class="modal-body">
                <p>Ürün silinecektir. Bu işlemin geri dönüşü yoktur!</p>
                <p>Emin misiniz?</p>
                <p class="debug-url"></p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Vazgeç</button>
                <a class="btn btn-danger btn-ok">SİL</a>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $('#confirm-delete').on('show.bs.modal', function(e) {
            $(this).find('.btn-ok').attr('href', '@Url.Action("Delete","Product",new {id=Model.ProductId})');
        });
    </script>
}

Ilk_Mvc_Projesi/Views/Product/Index.cshtml
@model List<Product>
<h2>Toplam Kayıt: @Model.Count</h2>

<a asp-controller="Product" asp-action="Create" class="btn btn-primary">Ekle</a>

<div class="row">
    <div class="col-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Kategori Adı</th>
                    <th>Ürün Adı</th>
                    <th>Fiyat</th>
                    <th>Tedarikçisi</th>
                    <th>Detay</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Category?.CategoryName</td> @*? işareti null ise çalıştırmaz*@
                        <td>@item.ProductName</td>
                        <td>@($"{item.UnitPrice:c2}")</td> @*c2 türkçe birim tl olarak gösterir*@
                        <td>@(item.Supplier ==  null ? Html.Raw(@"<u>Tedarikcisi Yok</u>") : item.Supplier.CompanyName)</td>
                        @*ikinci yöntem null gelme hatası*@
                        <td><a class="btn btn-info" asp-controller="Product" asp-action="Detail" asp-route-id="@item.ProductId">Detay</a></td>
                    </tr>

                }
            </tbody>
        </table>
        <input type="button" value="<" class="btn btn-success" id="btn-onceki" />
        @ViewBag.Page/@ViewBag.Limit
        <input type="button" value=">" class="btn btn-success" id="btn-sonraki" />
    </div>
</div>

@section Scripts{
    <script>
        var limit = @ViewBag.Limit;
        var page =@ViewBag.Page;
            $("#btn-onceki").click(function () {
                if (page>1) {
                    page -= 1;
                    var url = "Product/Index?page=" + page;
                    var url2 = '@Url.Action("Index", "Product", new {page=ViewBag.Page-1})';
                    window.location.href = url2;

                }
        });
        $("#btn-sonraki").click(function () {
            if (page < limit) {
                var url2 = '@Url.Action("Index", "Product", new {page=ViewBag.Page+1})';
                    window.location.href = url2;
            }

        });
    </script>
}

Ilk_Mvc_Projesi/Views/Product/Update.cshtml
@model ProductViewModel

<div class="bg-danger">
    <div asp-validation-summary="All">
    </div>
    </div>

<form method="post" asp-action="Update" asp-controller="Product">
    <input asp-for="ProductId" type="hidden" />
    <div class="row">
        <div class="col-3 text-black-50">Ürün Adı</div>
        <div class="col-3">
            <input asp-for="ProductName" class="form-control" />
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50">Fiyat</div>
        <div class="col-3">
            <input asp-for="UnitPrice" class="form-control" />
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50">Kategorisi</div>
        <div class="col-3">
            <select asp-for="CategoryId" asp-items="ViewBag.CategoryList" class="form-control"></select> @*KategoriId ve ViewBag eşleştiğinde gelicek*@
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50">Tedarikçi Firma</div>
        <div class="col-3">
            <select asp-for="supplierId" asp-items="ViewBag.SupplierList" class="form-control"></select>
        </div>
    </div>

    <div class="row">
        <div class="col-3 text-black-50"></div>
        <div class="col-5">
            <input type="submit" value="Guncelle" class="btn btn-danger" />
        </div>
    </div>
</form>